# Redirect default Netlify subdomain to primary domain

[[redirects]]
  from = "https://nselib.netlify.app/*"
  to = "https://www.nselib.com/:splat"
  status = 301
  force = true #COMMENT: ensure that we always redirect

[[redirects]]
  from = "/*"
  to = "/"
  status = 200
